[env]
CONAN_HOME = "{{config_root}}/build/conan"

[tools]
# Python 3.10 to avoid https://github.com/attardi/wikiextractor/issues/305
python = {version="3.10", virtualenv="build/python_venv"}

[settings]
experimental = true
python_compile = false
python_venv_auto_create = true
