[env]
CONAN_HOME = "{{config_root}}/build/conan"

[tools]
python = {version="3.11", virtualenv="build/python_venv"}

[settings]
experimental = true
python_compile = true
python_venv_auto_create = true
