[env]
CONAN_HOME = "{{config_root}}/conan.tmp"

[tools]
# Python 3.10 to avoid https://github.com/attardi/wikiextractor/issues/305
python = {version="3.10", virtualenv="venv.tmp"}

[settings]
experimental = true
python_compile = false
python_venv_auto_create = true
